[keyboard]
bindings = [
  { "key" = "Left",     "mods" = "Option",         "chars" = "\u001bb" }, # Skip word left
  { "key" = "Right",    "mods" = "Option",         "chars" = "\u001bf" }, # Skip word right
  { "key" = "Left",     "mods" = "Command",        "chars" = "\u001bOH", "mode" = "AppCursor" }, # Home
  { "key" = "Right",    "mods" = "Command",        "chars" = "\u001bOF", "mode" = "AppCursor" }, # End
  { "key" = "Back",     "mods" = "Command",        "chars" = "\u0015" }, # Delete line
  { "key" = "Back",     "mods" = "Option",         "chars" = "\u001b\u007f" }, # Delete word
  { "key" = "Left",     "mods" = "Command|Option", "chars" = "\u0002\u001b[D" },
  { "key" = "Right",    "mods" = "Command|Option", "chars" = "\u0002\u001b[C" },
  { "key" = "Up",       "mods" = "Command|Option", "chars" = "\u0002\u001b[A" },
  { "key" = "Down",     "mods" = "Command|Option", "chars" = "\u0002\u001b[B" },
  { "key" = "LBracket", "mods" = "Command|Option", "chars" = "\u0002p" },
  { "key" = "RBracket", "mods" = "Command|Option", "chars" = "\u0002n" },
]

[font]
size = 14

[font.normal]
family = "BerkeleyMono Nerd Font"

[window]
decorations = "none"
padding = { x = 7, y = 0 }

