#!/bin/bash

if ! command -v blueutil &> /dev/null; then
    echo "ERROR: blueutil not installed."
    exit 1
fi
AIRPODS_REGISTRY=$(blueutil --paired | grep "AirPods")
if [ -z "$AIRPODS_REGISTRY" ]; then
    echo "ERROR: AirPods not paired."
    exit 1
fi

AIRPODS_UUID=$(echo "$AIRPODS_REGISTRY" | awk '{ print $2 }' | sed -e 's/,$//')
AIRPODS_NAME=$(echo "$AIRPODS_REGISTRY" | sed -E 's/.* name: "([^"]+)".*/\1/')

IS_CONNECTED=$(blueutil --is-connected "$AIRPODS_UUID")

if [ "$IS_CONNECTED" == "1" ]; then
    echo "$AIRPODS_NAME already connected."
    exit 0
fi

echo "Initiated process to connect $AIRPODS_NAME"
blueutil --connect "$AIRPODS_UUID"

