#!/bin/bash
# I like docker-compose to be a little tidier... So this overrides the docker
# executable in order to export the COMPOSE_PROJECT_NAME to the name of the
# current directory based on ~/Developer

set -e -o pipefail
if [[ "$1" == "compose" ]]; then
    wd=$(pwd)
    if [[ "$wd" =~ ^/Users/$USER/Developer.* ]]; then
        wd=$(pwd | sed "s/\/Users\/$USER\/Developer\///" | sed "s/\//-/g")
        export COMPOSE_PROJECT_NAME="$wd"
    else
        unset COMPOSE_PROEJCT_NAME
    fi
fi
exec $(brew --prefix)/opt/docker/bin/docker "$@"
